siimon/prom-client

- README.md
- index.js
- lib/summary.js
- package.json
- test/summaryTest.js
I've added a summary metric type to report to Prometheus. Added a dependency to TDigest to calculate the percentiles. Also reports count and sum of each label.
Also includes tests for the summary metric type.
> Add summary metric type

- lib/histogram.js
- lib/summary.js
- package.json
- test/histogramTest.js
- test/pushgatewayTest.js
- test/summaryTest.js
Added function to reset the values on a histogram and summary metric. Also enabled all tests again, because only the push-gateway tests were executed.
> Allow resetting histogram and summary metrics

- lib/summary.js
- test/summaryTest.js
Small bug-fix to prevent Prometheus scrapers to fail when a summary value is reset and it's percentiles have no value anymore.
> Summary percentile values should be 0 instead of undefined after reset

- README.md
- lib/gauge.js
- lib/histogram.js
- lib/summary.js
- test/gaugeTest.js
- test/histogramTest.js
- test/summaryTest.js
One common use case I've run into while using Prometheus at Tinder is having a label for success/failure on a single metric, like the following:
```javascript
var promClient = require('prom-client');
var metric = promClient.metric('metric_name', 'metric_help', ['success_response']);
var timer = metric.startTimer();
someFunction((err, result) => {
if (err) {
timer({ success_response: 'ERROR' });
console.log('uh-oh');
// do error logic
} else {
timer({ success_response: 'SUCCESS' });
console.log('yay!');
// do success logic
}
})
```
With the original code, it seemed like there wasn't a very clean way to handle this; the only way we had solved the problem before was by creating two timers (eg, a `successTimer` and an `errorTimer`) and only ever calling one of the timers later, but that seems …
> Add post-timer labels (#1)

- README.md
- index.js
- lib/counter.js
- lib/defaultMetrics.js
- lib/gauge.js
- lib/histogram.js
- lib/metrics/osMemoryHeap.js
- lib/metrics/osMemoryHeapLinux.js
- lib/metrics/processCpuTotal.js
- lib/metrics/processMaxFileDescriptors.js
- lib/metrics/processOpenFileDescriptors.js
- lib/metrics/processStartTime.js
- lib/summary.js
- test/defaultMetrics.js
Hi there!
All Prometheus clients are recommended to export some basic metrics https://prometheus.io/docs/instrumenting/writing_clientlibs/#standard-and-runtime-collectors.
Descriptions stolen from the official Go client, https://github.com/prometheus/client_golang/blob/master/prometheus/process_collector.go.
This PR adds all of them, although most will only work on Linux.
No tests added in case you're not interested in the addition.
Example file for testing:
```js
var prom = require('./');
prom.defaultMetrics([], 500);
setInterval(function () {
console.log(prom.register.metrics());
}, 500);
```
Example Dockerfile for testing
```dockerfile
FROM node:6
COPY . .
CMD ["node", "testfile.js"]
```
Example output of running app:
```
process_cpu_seconds_total 33.73
process_start_time_seconds …
```
> Add the officially recommended metrics

- README.md
- lib/defaultMetrics.js
- lib/metrics/eventLoopLag.js
- lib/metrics/processHandles.js
- lib/metrics/processRequests.js
- package.json
- test/defaultMetrics.js
- test/gaugeTest.js
- test/metrics/eventLoopLagTest.js
- test/metrics/processHandlesTest.js
- test/metrics/processRequestsTest.js
Builds on top of #25. I'll rebase after that's merged (or you can just merge this).
See the last commit in this PR for the diff in the meantime.
Ideas for extra metrics very much welcome!
At work we show more of `memoryUsage` (but I think those are covered in #25, although just for Linux) and `os.loadAvg[0]`, but I'm not sure if those are actually useful?
> Extra metrics

- .editorconfig
- .eslintrc
- lib/defaultMetrics.js
- lib/histogram.js
- lib/metrics/eventLoopLag.js
- lib/metrics/heapSizeAndUsed.js
- lib/metrics/osMemoryHeap.js
- lib/metrics/osMemoryHeapLinux.js
- lib/metrics/processCpuTotal.js
- lib/metrics/processHandles.js
- lib/metrics/processMaxFileDescriptors.js
- lib/metrics/processOpenFileDescriptors.js
- lib/metrics/processRequests.js
- lib/metrics/processStartTime.js
- lib/pushgateway.js
- lib/register.js
- lib/summary.js
- lib/util.js
- package.json
- test/.eslintrc
- test/defaultMetrics.js
- test/metrics/eventLoopLagTest.js
- test/metrics/heapSizeAndUsedTest.js
- test/metrics/processHandlesTest.js
- test/metrics/processRequestsTest.js
Noticed that there's horribly mixed spaces and tabs (most of the spaces come from my PR, but not all).
This enforces tabs using eslint, and adds an editorconfig to help IDEs use it automatically.
The second commit upgrades to latest major of eslint. Breaking is mostly dropping support for node older than 4, which is why I included a dep that checks for the node version
> Enfore tabs as indentation

- README.md
- lib/register.js
- test/registerTest.js
Builds on #41 
By having a single key, we can now easily remove a metric.
If you don't want #41, I can use the array as well (`removeMetricByName`). I prefer this way, though 😄
> Remove single metric

- lib/metrics/processMaxFileDescriptors.js
The value read from the file includes a new line, this is being passed
on tot he value, and printed in theoutput. It doesn't cause a problem
for scraping right now, but it could break things in the future.
> Remove newline from process_max_fds value

- README.md
As exported in register.js:
```javascript
module.exports = {
...
clear: clearMetrics,
```
> Fix typo in README (register.clearMetrics -> register.clear())

- lib/metrics/processMaxFileDescriptors.js
- test/defaultMetrics.js
Currently it's always present. On my Mac, it's there, but never assigned.
Ref #36 
/cc @tcolgate
> Only register the `max_fds` if the OS is supported

- lib/metrics/processCpuTotal.js
When using process.cpuUsage(lastCpuUsage), only the delta is returned.
One either needs to add this to lastCpuUsage manually, or do the
math operations.
This should fix issue #57
Signed-off-by: Simen Bekkhus (@SimenB) <sbekkhus91@gmail.com>
Signed-off-by: Arne-Christian Blystad (@Blystad) <arne.christian@blystad.me>
> cpu usage: Fix increasing cpu usage

- index.d.ts
- package.json
I've just started poking around with Typescript and found there were a few problems with the definitions provided by this package. I'm _very_ new to TS definitions, so all feedback is welcomed.
A summary of the changes:
- The existing index.d.ts file isn't published with npm, so consumers of the package can't use it.
- It appears as though `[number]` was used to signify an array of numbers, however that's a tuple containing one number. `number[]` is the correct syntax.
- some method overloads were defined in a way which is apparently not good. Following the instructions in the [dos and don'ts guide](http://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html), I added optional parameters where possible, and rearranged overloads to put the more specific overload …
> Typescript improvements

- README.md
- lib/register.js
- test/registerTest.js
We create a metric inside a function, which might be called multiple times (with different labels). Instead of introducing some sort of state handling into our module, it'd be prettier if we could just fetch a the metric from the register itself.
> Add method to get a registred metric

- README.md
[This section](https://github.com/siimon/prom-client/blob/089aa1de703ef1648df3ae48f974a8ff74aa5602/lib/pushgateway.js#L81-L85) fails if the provided Pushgateway URL does not include the scheme, which the example did not include.
I don't see any reason to not require it so better to just update the documentation.
> Added scheme to Pushgateway example code.

- lib/defaultMetrics.js
- lib/metrics/heapSpacesSizeAndUsed.js
- package.json
- test/metrics/heapSpacesSizeAndUsedTest.js
Hi. In this PR I've added detailed v8 heap spaces metrics. V8 has 5 main spaces (named in brackets): 
* New-space (new-space): Most objects are allocated here. New-space is small and is designed to be garbage collected very quickly, independent of other spaces.
* Old-pointer-space (old-space): Contains most objects which may have pointers to other objects. Most objects are moved here after surviving in new-space for a while.
* Old-data-space (old-space): Contains objects which just contain raw data (no pointers to other objects). Strings, boxed numbers, and arrays of unboxed doubles are moved here after surviving in new-space for a while.
* Large-object-space (large-object-space): This space contains objects which are larger than the size limits of other spaces. Each object gets its own …
> Detailed nodejs v8 heap space metrics

- lib/pushgateway.js
- test/pushgatewayTest.js
Hi,
I've done a small adjustment in `prom-client`, that you might be interested in merging into main branch.
In my setup, I run Pushgateway through proxy that requires basic client authentication, so I've modified the way requests are being made, to provide auth configuration through Pushgateway URL.
It's just a basic support for the URL format: `https://<username>:<password>@example.org`
Actual implementation just uses the standard NodeJS `url` module to construct HTTP request parameters that are not stripped of username and password parts of URL provided to Pushgateway object constructor.
> Passing authentication data through URI, when pushing to Pushgateway

- lib/gauge.js
- lib/histogram.js
- lib/summary.js
- package.json
Using `new Date()` for timing is susceptible to clock reset issues via
ntp as well as leap seconds, resulting in incorrect or even negative
values. `process.hrtime()` is the recommended method of timing things
in node because it uses monotonic time and is not susceptible to issues
around wall clock resets. It also has the added benefit of being higher
resolution, although that wont really effect histograms/summaries much.
https://nodejs.org/api/process.html#process_process_hrtime_time
I had to use the pre release of sinon 2.x to get the tests to work for
this change, sinon 1.x does not support fake hrtime. As this is
just a dev dependency, I hope this is alright.
> Use hrtime for timing

- README.md
- lib/defaultMetrics.js
- lib/metrics/version.js
- test/metrics/versionTest.js
It'll look like this:
```
nodejs_version_info{version="v6.10.0",major="6",minor="10",patch="0"} 1
```
Inspired by https://github.com/prometheus/client_java/commit/bdc6f2507a81029c1aec6cd8b5276661bb6c7ee1
Java looks like:
```
jvm_info{version="1.8.0_121-b13",vendor="Oracle Corporation",} 1.0
```
> Include node.js version in output

- lib/metrics/heapSizeAndUsed.js
- lib/metrics/helpers/safeMemoryUsage.js
- lib/metrics/osMemoryHeap.js
According to #67 `process.memoryUsage()` can throw exceptions sometimes. It was handled in one file, but  not in `osMemoryHeap.js`. I've moved wrapped function into separate helper module to use it in both cases.
> Fix exception handling for process.memoryUsage()

- index.d.ts
I'm sorry, yesterday I've made a PR with "outdated" typing fix (forgot to push correct fix into my fork). Obviously `getSingleMetric` function returns one of Counter, Gauge, Summary or Histogram. For those reasons I've also added export type called `Metric` which corresponds to one of that types. It is very handy when you're writing something in typescript.
> Fix getSingleMetric type and add exported Metric type

- lib/metrics/heapSpacesSizeAndUsed.js
I've found out that heap space metrics with labels can shadow simple heap stats. So I think it's better to move them to other "namespace".
> Fix shadowing of nodejs_heap_size_*_bytes by spaces size

- lib/defaultMetrics.js
See #86 
This currently errors out, because of what #86 is trying to fix. So merging first that then rebasing this should make it green.
I never considered the case where the included metrics could clash when adding the throw...
This change makes the first run add all, and only on subsequent invocations of the function will it clean out the old metric
> Throw if there are duplicate default metric names

- README.md
- example/server.js
- lib/register.js
- test/registerTest.js
I've recently faced an issue: I needed to display 2 different metrics on 2 different endpoints (they would be fetched with two different intervals by Prometheus). `prom-client` doesn't provide a way to get a single metric as a Prometheus string. So I've implemented it.
I changed a `register.getSingleMetric()` to return a Prometheus string, added `register.getSingleMetricObject()` to get metric by name (instead of `register.getSingleMetric()`), provided an example of these changes and README entry for them and fixed tests to reflect these changes.
There would be 1 breaking change (the `register.getSingleMetric()` would return a string instead of an object), I think my naming is better (if you have other ideas how to name methods, please tell).
> Displaying a single metric as a Prometheus string

- README.md
- lib/counter.js
- lib/gauge.js
- lib/histogram.js
- lib/summary.js
- lib/util.js
- test/counterTest.js
- test/gaugeTest.js
- test/histogramTest.js
- test/summaryTest.js
As discussed in #100, it's been a mess to add new functionality to the metrics because of parameter bloat in the constructor for each metric.
This PR tries to address this, replacing the old 'one parameter for each parameter' with an object that can hold all parameters needed for the constructor. This will make it easier to add new functionality in the future.
This PR should be backwards compatible, but the old one should be deprecated from now on.
@SimenB @SkeLLLa @eljasala could anyone of you have a look?
> Use object instead of separate params as constructor parameters

- README.md
- index.d.ts
- index.js
- lib/counter.js
- lib/defaultMetrics.js
- lib/gauge.js
- lib/histogram.js
- lib/pushgateway.js
- lib/register.js
- lib/registry.js
- lib/summary.js
- test/counterTest.js
- test/gaugeTest.js
- test/histogramTest.js
- test/pushgatewayTest.js
- test/summaryTest.js
Currently the library registers all metrics in the global registry without a way to override this behavior & there isn't support for other registries. There are couple of downsides with this that we came across (there might be more):
* It's problematic for modules to use this library in the current state. This + #99 should make it easier for modules to expose metrics to application and application could then decide which ones it wants to expose
* If you want to expose different set of metrics on different endpoints, you would need to hardcode the metrics you want to expose on both endpoints.
I do realize there is still at least one problem left with the modules using library directly: When merging different registries, it's possible that there are clashes on names and there isn't …
> Non-global registries

- lib/validation.js
- test/validationTest.js
I had a typo when using the object form of labels. Would be nice if it the error included info about what label I used, and which were available
> Include name of unknown label in error

- CHANGELOG.md
- README.md
- index.d.ts
- lib/registry.js
- test/registerTest.js
Makes it possible to merge multiple registries - handy when you want to expose modules registers within your app for example.
> Merge registries

- lib/metrics/eventLoopLag.js
- lib/metrics/heapSizeAndUsed.js
- lib/metrics/heapSpacesSizeAndUsed.js
- lib/metrics/osMemoryHeap.js
- lib/metrics/osMemoryHeapLinux.js
- lib/metrics/processCpuTotal.js
- lib/metrics/processHandles.js
- lib/metrics/processMaxFileDescriptors.js
- lib/metrics/processOpenFileDescriptors.js
- lib/metrics/processRequests.js
- lib/metrics/processStartTime.js
- lib/metrics/version.js
Seeing as the non-object constructors are soft deprecated, we should not use them ourselves.
> Use object constructor for built in metrics

- package.json
- test/gaugeTest.js
- test/histogramTest.js
- test/summaryTest.js
Since we only use sinon for time now that jest is used for tests, we can use lolex directly (it's what sinon uses under the hood for time stuff).
> Replace sinon with lolex

- CHANGELOG.md
- README.md
- index.d.ts
- lib/registry.js
- test/registerTest.js
I believe this is a pretty good solution for #83 
It's simple, doesn't break any APIs, allows you to configure static labels per registry, and defaulted values can be overridden.
Let me know if this wasn't what you were thinking about this, or if there are any styling considerations I should be changing.
Thanks!
> Add support for default labels

- CHANGELOG.md
- README.md
- index.d.ts
- lib/counter.js
- lib/defaultMetrics.js
- lib/gauge.js
- lib/histogram.js
- lib/metrics/eventLoopLag.js
- lib/metrics/heapSizeAndUsed.js
- lib/metrics/heapSpacesSizeAndUsed.js
- lib/metrics/osMemoryHeap.js
- lib/metrics/osMemoryHeapLinux.js
- lib/metrics/processCpuTotal.js
- lib/metrics/processHandles.js
- lib/metrics/processMaxFileDescriptors.js
- lib/metrics/processOpenFileDescriptors.js
- lib/metrics/processRequests.js
- lib/metrics/processStartTime.js
- lib/metrics/version.js
- lib/summary.js
- test/defaultMetricsTest.js
Maybe take an object to `collectDefaultMetrics`? I'm going to tackle custom labels for the default metrics now, yet another option and it gets quite hairy
> Allow registering default metrics to other registries

- CHANGELOG.md
- lib/counter.js
- lib/gauge.js
- lib/histogram.js
- lib/summary.js
- test/__snapshots__/registerTest.js.snap
- test/counterTest.js
- test/gaugeTest.js
- test/histogramTest.js
- test/metrics/versionTest.js
- test/registerTest.js
- test/summaryTest.js
Fixing #118 
Added fixes for Counters, Gauges and Histograms.. Summary I'm not sure what to do about tbh.. After a quick look it's not an easy fix.
> Init metrics to zero

- CHANGELOG.md
- index.d.ts
Fixed mismatch type definition. I have checked that the corresponding test case is using `register` instead of `registry`.
> Fixed typing of DefaultMetricsCollectorConfiguration in definitions file

- CHANGELOG.md
- README.md
- index.d.ts
- lib/pushgateway.js
- lib/registry.js
- test/registerTest.js
As of pushgateway 0.4, timestamps are no longer accepted when pushing.
See: https://github.com/prometheus/pushgateway/pull/119
> Compatibility with pushgateway 0.4

- CHANGELOG.md
- lib/counter.js
- lib/gauge.js
- lib/histogram.js
- lib/summary.js
- lib/util.js
- test/__snapshots__/counterTest.js.snap
- test/__snapshots__/gaugeTest.js.snap
- test/__snapshots__/histogramTest.js.snap
- test/__snapshots__/summaryTest.js.snap
- test/counterTest.js
- test/gaugeTest.js
- test/histogramTest.js
- test/summaryTest.js
`Error` only expects one argument, the `message`, which means that the invalid values were lost in the second argument.
> Include invalid values in the error messages

- .eslintrc
- CHANGELOG.md
- README.md
- example/cluster.js
- example/server.js
- index.d.ts
- index.js
- lib/cluster.js
- lib/counter.js
- lib/gauge.js
- lib/histogram.js
- lib/metricAggregators.js
- lib/metrics/eventLoopLag.js
- lib/metrics/processStartTime.js
- lib/metrics/version.js
- lib/summary.js
- lib/util.js
- test/aggregatorsTest.js
- test/clusterTest.js
Hello! This is an opening gambit for supporting aggregated metrics for use with node's `cluster` module. It's not ready for merge; looking for feedback first as to whether or not this would go in prom-client or a separate module that wraps prom-client.
It's only lightly tested, and there are no unit tests yet.
I made the changes completely isolated in a separate file that is not loaded by default. From reading issues #82 and #80, I wasn't sure if a PR that provides this functionality would be accepted, so I wanted the changes to work if the functionality was provided as a separate Node.js module. However, that means that [the `metric.aggregate` stuff](https://github.com/siimon/prom-client/compare/master...zbjornson:cluster?expand=1#diff-0faa53fc02580d5de2ebb484c41d691cR98) is a bit ugly. …
> Cluster support

- lib/cluster.js
The `cluster.on('message')` function doesn't have the worker as the first argument in node < 6. To do this, the official way is to check the number of arguments received. However, because this is using a fat arrow function (`() => {}`), the variable `arguments` is hoisted outside the scope so the actual arguments
has a length of 5.
If you run the old version of the code in [Babel](http://bit.ly/2wbApcb) this shows the problem:
```javascript
cluster.on('message', (worker, message) => {
if (arguments.length === 2) {
// pre-Node.js v6.0
message = worker;
worker = undefined;
}
});
```
This gets compiled to:
```javascript
var _arguments = arguments;
cluster.on('message', function (worker, message) {
if (_arguments.length === 2) {
// pre-Node.js v6.0
message = worker;
worker = undefined;
}
}); …
```
> Bugfix - cannot get cluster info in node version < 6

- CHANGELOG.md
- index.d.ts
- package.json
* add missing contentType field to Registry class
* interval is incorrect, timeout is the correct field
* various jsdoc fixes
* update to latest TypeScript compiler
> Bugfix - update TypeScript definitions

- CHANGELOG.md
- README.md
- index.d.ts
- lib/counter.js
- lib/gauge.js
- lib/registry.js
- test/counterTest.js
- test/gaugeTest.js
- test/registerTest.js
I needed a way to reset metrics, without removing the metric instances, see also #145. 
This solution is not completely tested, but I would like to know if this is a right way to go.
> reset Metrics

- CHANGELOG.md
- lib/counter.js
- package.json
- test/counterTest.js
set default hash to empty string (`''`) -- same as `hashObject({})`
> fix for issue #156

- CHANGELOG.md
- lib/cluster.js
- test/clusterTest.js
Sorry for the delay, forgot about this. Small change aside from indenting (try [ignoring whitespace](https://github.com/siimon/prom-client/pull/159/files?w=1)).
Fixes #155
> Lazily initialize cluster event listeners

- CHANGELOG.md
- lib/cluster.js
- test/clusterTest.js
Small behavior change: Don't resolve/reject the promise returned by `clusterMetrics` if a callback is provided to that function. This prevents `UnhandledPromiseRejectionWarnings` from occurring if you're using callbacks.
> Only resolve/reject `clusterMetrics` promise if no callback is provided

- CHANGELOG.md
- lib/metrics/osMemoryHeapLinux.js
You have to multiply memory reported by the `/proc/self/status` by 1024, not 1000; because it's in KiB.
Proof:
```
$ ps -o vsz -p 15301
VSZ
13820
$ grep VmSize /proc/15301/status
VmSize:    13820 kB
$ man ps | grep vsz             
%z     vsz      VSZ
vsz and rss.
vsize       VSZ       see vsz.  (alias vsz).
vsz         VSZ       virtual memory size of the process in KiB (1024-byte
```
Replace 15301 with the PID of your choice.
> fixed invalid memory report on linux

- CHANGELOG.md
- lib/registry.js
- test/registerTest.js
registry.getMetricsAsJSON should merge metric labels and registry default labels
> Cluster metrics aggregation ignores default labels

- CHANGELOG.md
- lib/gauge.js
I think this is the only instance where this is incorrect.
Breaking change
Fixes #167
> Use base units (seconds) for current time in gauge

- lib/util.js
- lib/validation.js
- package.json
Both Jest and lint-staged has dropped node 4 (same as us now), and prettier was locked down
> upgrade dependencies

- CHANGELOG.md
- lib/gauge.js
- lib/histogram.js
- lib/summary.js
- test/gaugeTest.js
- test/histogramTest.js
- test/summaryTest.js
> Fix `startTimer` utility to not mutate passed `startLabels` object

- CHANGELOG.md
- lib/metricAggregators.js
- test/clusterTest.js
When aggregating registries, the `aggregator` property of the metrics is lost. This PR aims to repopulate it with the aggregator property of the first metric, for better consistency.
This will prevent the `AggregatorRegistry#aggregate` function from breaking when attempting to aggregate an already-aggregated registry.
> Fix aggregator method being lost when aggregating several registries

- CHANGELOG.md
- README.md
- lib/defaultMetrics.js
- lib/metrics/eventLoopLag.js
- lib/metrics/heapSizeAndUsed.js
- lib/metrics/heapSpacesSizeAndUsed.js
- lib/metrics/osMemoryHeap.js
- lib/metrics/osMemoryHeapLinux.js
- lib/metrics/processCpuTotal.js
- lib/metrics/processHandles.js
- lib/metrics/processMaxFileDescriptors.js
- lib/metrics/processOpenFileDescriptors.js
- lib/metrics/processRequests.js
- lib/metrics/processStartTime.js
- lib/metrics/version.js
- test/defaultMetricsTest.js
Adds the ability to provide a `prefix` string to the default metrics.
This helps in our use-case, where we have many applications residing on a single Prometheus instance and need to easily identify which metrics belong to which application.
> Add optional prefix to default metrics

- index.d.ts
adding prefix to DefaultMetricsCollectorConfiguration, related to the release v11.1.0.
> Complementing prefix in index.d.ts

- CHANGELOG.md
- lib/gauge.js
- lib/registry.js
- lib/util.js
- test/gaugeTest.js
- test/registerTest.js
This should fix https://github.com/siimon/prom-client/issues/168
> Allow setting Gauge values to NaN.

- lib/metrics/processOpenFileDescriptors.js
- package-lock.json
- package.json
- test/metrics/processOpenFileDescriptorsTest.js
This is a follow-up of my PR #201. As pointed out by @SimenB [in the comments](https://github.com/siimon/prom-client/pull/201#discussion_r199135034), the Sinon dependency is not necessary to mock `process.platform` in order to make the `processOpenFileDescriptors` unit test pass on any platform.
This PR removes the Sinon dependency by using Jest to do the same thing.
Best regards!
> Remove Sinon dependency

- CHANGELOG.md
- appveyor.yml
- lib/counter.js
- lib/util.js
- package-lock.json
- package.json
This adds support for yaml and removes the silly newlines in `package{-lock}.json` to avoid conflicts with npm
> chore: upgrade prettier

- CHANGELOG.md
- lib/histogram.js
When profiling histogram scraping I discovered that the major bottleneck is creating a clone of the accumulator in reduce. We should not actually need to skip mutation.
You can see the benchmark of `concat` vs `push` here:  https://codeburst.io/jsnoob-push-vs-concat-basics-and-performance-comparison-7a4b55242fa9
This should address https://github.com/siimon/prom-client/issues/216
I used this test script to profile.
```js
const prom = require('prom-client');
const _ = require('lodash');
const histogram = new prom.Histogram({
name: 'histogram',
help: 'histogram',
labelNames: ['a', 'b', 'c', 'd'],
});
_.times(2, a => {
_.times(3, b => {
_.times(10, c => {
_.times(100, d => {
const end = histogram.startTimer();
end({a,b,c,d});
});
});
});
});
console.log('Starting metrics');
const now = …
```
> Fix histogram scrape performance

- .eslintrc
- lib/cluster.js
- lib/counter.js
- lib/defaultMetrics.js
- lib/gauge.js
- lib/histogram.js
- lib/metricAggregators.js
- lib/pushgateway.js
- lib/registry.js
- lib/summary.js
- package-lock.json
- package.json
This will warn us against unsupported features without waiting for CI
to run
Also upgrade all dated dependencies
Motivation is if we use e.g. Object.entries, we normally have to wait for CI to fail. Now we'll get a linting error in our IDE or precommit:
```
31:4  error  The 'Object.entries' is not supported until Node.js 7.0.0. The configured version range is '>=6.1'  node/no-unsupported-features/es-builtins
```
> chore: add eslint-plugin-node

- CHANGELOG.md
- lib/histogram.js
- lib/registry.js
I discovered another performance optimization we can perform, which is to mutate the `labels` and avoid `Object.assign` where we can in hot paths.
```
❯ node benchmarks/index.js
Progress:
published#registry#getMetricsAsJSON x 1,819 ops/sec ±4.51% (80 runs sampled)
published#registry#metrics x 1,301 ops/sec ±5.13% (76 runs sampled)
local#registry#getMetricsAsJSON x 9,025 ops/sec ±4.71% (82 runs sampled)
local#registry#metrics x 2,968 ops/sec ±3.59% (85 runs sampled)
Results:
╔══════════════════╤════════════════════════════╤═══════════════════════════╗
║ registry         │ published                  │ local                     ║
╟──────────────────┼────────────────────────────┼───────────────────────────╢
║ getMetricsAsJSON │ 1819.383794048214 ops/sec  │ 9024.761535386682 ops/sec ║ …
```
> Mutate labels to avoid excessive object cloning.

- CHANGELOG.md
- package-lock.json
####Background
I found that the child dependency `merge` had eight vurnabilities so I fixed those with the help of npm 6's audit.
```sh
=== npm audit security report ===                        
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ merge                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ jest [dev]                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ jest > jest-cli > …
```
> Matt jarrett fix child dependency with vulnerability

- benchmarks/index.js
- benchmarks/summary.js
- lib/registry.js
- lib/util.js
This improves the performance of `hashObject()` and `getMetricAsPrometheusString()`.
I also added a benchmark for the metric type Summary.
Here is the benchmark result:
```bash
⚠ registry ➭ getMetricsAsJSON#1 with 64 is 0.5266% acceptably slower.
⚠ registry ➭ getMetricsAsJSON#2 with 8 is 1.965% acceptably slower.
⚠ registry ➭ getMetricsAsJSON#2 with 4 and 2 with 2 is 0.4088% acceptably slower.
⚠ registry ➭ getMetricsAsJSON#2 with 2 and 2 with 4 is 1.382% acceptably slower.
✓ registry ➭ getMetricsAsJSON#6 with 2 is 2.998% faster.
✓ registry ➭ metrics#1 with 64 is 10.60% faster.
✓ registry ➭ metrics#2 with 8 is 13.43% faster.
✓ registry ➭ metrics#2 with 4 and 2 with 2 is 8.662% faster.
✓ registry ➭ metrics#2 with 2 and 2 with 4 is 8.565% faster.
✓ registry ➭ metrics#6 with 2 is 4.454% …
```
> Performance improvement

- CHANGELOG.md
- index.d.ts
- lib/counter.js
- lib/gauge.js
- lib/histogram.js
- lib/summary.js
- lib/util.js
- test/__snapshots__/counterTest.js.snap
- test/__snapshots__/gaugeTest.js.snap
- test/__snapshots__/histogramTest.js.snap
- test/__snapshots__/summaryTest.js.snap
- test/counterTest.js
- test/gaugeTest.js
- test/histogramTest.js
- test/summaryTest.js
This addresses #187
This implements a `remove()` method on each metric type, based on [Prometheus "Writing Client Libraries" section on labels](https://prometheus.io/docs/instrumenting/writing_clientlibs/#labels)
> Add remove() method for handling dynamic labels

- CHANGELOG.md
- lib/cluster.js
A cluster worker can still be in the list of workers even if its IPC channel has closed (e.g. when the worker exits abruptly). Fix by checking that its IPC channel is open before sending a message.
This happens extremely infrequently (less than once a month for us, running several hundred VMs scraping every 10 seconds), but I've tested in an artificial situation that this makes communication safe:
```js
const cluster = require("cluster");
if (cluster.isMaster) {
for (let i = 0; i < 4; i++) {
const worker = cluster.fork();
// THIS SHOULDN'T LOG WITH THE FIX
worker.on("error", err => console.log("worker error", err));
}
cluster.on("exit", (worker, code, signal) => {
setTimeout(() => cluster.fork(), 500);
});
setInterval(() => {
for (const id in cluster.workers) {
if …
```
> Fix rare ERR_IPC_CHANNEL_CLOSED bug in cluster mode

- CHANGELOG.md
- lib/metrics/helpers/processMetricsHelpers.js
- lib/metrics/processHandles.js
- lib/metrics/processRequests.js
- test/metrics/processHandlesTest.js
- test/metrics/processRequestsTest.js
Hello @siimon 
In my project I found it quite useful to monitor not only total number of active requests and handles(process._getActiveRequests()/process._getActiveHandles()), but also split them by type.
If you see that number of active handles is growing but you dont know the handle type - it did not help you much track down the problem.
```
nodejs_active_handles{type="WriteStream"} 2 1556027670456
nodejs_active_handles{type="Server"} 2 1556027670456
nodejs_active_handles{type="Socket"} 2 1556027670456
```
With this patch you will  see what exactly is going wrong with your node js app.
I kept original nodejs_active_handles_total/nodejs_active_requests_total metrics for backward compatibility. So there is no breaking changes in this pull request
> Split process request and process handles by type

- package-lock.json
- package.json
- tsconfig.json
Been a long time. We still have some `audit` warnings due to the dependency on `npm` via `@clevernature/benchmark-regression`.
/cc @nowells (I don't think you can do anything about it)
> chore: bump dependencies

- index.d.ts
- index.js
Hi! Thanks so much for this useful library!
We're using it in https://github.com/badges/shields, which is a moderately complex project that hosts the application for https://shields.io/, which can also be used for self-hosting and in a bunch of other ways. We have Prometheus enabled in production, however it's turned off for unit testing.
We have almost 300 contributors, so there are a lot of different people working on the codebase. We also have about 300 services, which are the integrations we provide for various badges.
I'm auto-generating a prometheus metric name from one of these class names and since I'm discovering it's really easy to accidentally generate one that isn't valid, I'd like to add a check to our service validator that the class names are valid – and to do this without …
> Add validateMetricName() to the public interface

- CHANGELOG.md
- README.md
- index.d.ts
- lib/defaultMetrics.js
- lib/metrics/heapSizeAndUsed.js
- lib/metrics/processHandles.js
- test/defaultMetricsTest.js
Some timestamps can now be turned off by the user.
We have a server that does not have the correct time set.
Prometheus ignores these metrics because timestamps are too far in the future.
We currently can not change the server time so we are not collecting these critical metrics.
> feat: add option to disable timestamps on defaultMetrics

- lib/metrics/helpers/processMetricsHelpers.js
Fix for #270 
I can not reproduce this  bug in my environment, but I suppose that it can happen due to the null values returned by process._getActiveHandles().
> fix: guard against missing constructor

- CHANGELOG.md
- lib/registry.js
- test/registerTest.js
The defaultLabels feature is buggy when used in combination
with the `.labels()` sub counter feature.
We mutate the object in the serialization implementation which
means the next time you observe the value the labels object has
been incorrectly mutated.
The functionality of `.labels()` is supposed to be the caching
of the labels object itself instead of constantly re-using it.
I may actually be the only one using the caching feature of the
`.labels()` method which is why this bug was not caught earlier.
The `.labels()` method is not broken if you use it as
```
histogram.labels(...).observe(int)
```
But is broken if you do
```
class Foo {
constructor() {
this.myHistogram = histogram.labels(...)
}
method() {
this.myHistogram.observe(int)
}
}
```
> fix: avoid mutation bug in registry

- CHANGELOG.md
- index.d.ts
- lib/summary.js
As already described in #142 the Summary is leaking memory. This fix will call the compress method of t-digist. To prevent compressing a too small set of measurements and increasing performance, it will call the compress method every 1000 measurements by default. You can also specify another count with option `compressCount` in the Summary options.
> Compress t-digest to prevent memory leakage

- .travis.yml
- CHANGELOG.md
- appveyor.yml
- package.json
v6 is consistently failing in Travis, and is also EOL. Added v12 and 13.
> chore: fix CI/drop support for Node.js 6

- CHANGELOG.md
- lib/registry.js
- test/registerTest.js
Bug introduced at #220 and fixed for .getMetricAsPrometheusString() at #273.
Fixes #287
> fix: avoid mutation bug in registry.getMetricsAsJSON()

- CHANGELOG.md
- package.json
The husky pre-commit script enforces use of TAB in .json files, and
package.json is using SPC SPC. This isn't noticable until someone
changes one line in the package.json, at which point the entire file
gets reindented.
-----
I did this by adding a single TAB to the start of one line in package.json, then git commiting it, this triggered husky's git-commit hook to reformat the file, et voila, this is the result.
> chore: reindent package.json

- CHANGELOG.md
- lib/metrics/processMaxFileDescriptors.js
- test/metrics/maxFileDescriptorsTest.js
Fix https://github.com/siimon/prom-client/issues/311
In case anyone is wondering why I don't check for a exact match against the ulimit output, instead of just for "reasonableness", its because there isn't really any way to check the ulimit for the current process other than reading `/proc/self/limits`. Shelling out to ulimit would gives the correct value, but for the child shell... but that ulimit will be the default for /bin/sh, which might not be the ulimit for the current jest process (and is not on my machine, my login /bin/zsh has a different ulimit than /bin/sh).
> fix: process_max_fds is process limit, not OS

- .travis.yml
- CHANGELOG.md
- package.json
Node.js 8.x is EOL. Since dropping support for a Node.js release line is
semver-major, might as well drop 8.x at the same time as 6.x.
cf. 32920d0e1d946197b
> chore: drop support for Node.js 8.x

- appveyor.yml
Drop 8.x from appveyor's supported platforms.
Travis was dropped in #315, but appveyor was overlooked.
See:
- https://github.com/siimon/prom-client/pull/315
- https://github.com/siimon/prom-client/pull/316#issuecomment-579440589
> chore: drop support for Node.js 8.x (appveyor)

- .gitattributes
- .github/workflows/nodejs.yml
- README.md
- package.json
Sets up GH Actions. Can replace both travis and appveyor.
It's (way) faster and has better integration with GH itself, which might matter if we ever wanna do releases from CI or some such. It also automatically picks up typescript and eslint errors and adds inline annotations, which is nice 🙂
> chore: add GH Actions CI

- CHANGELOG.md
- README.md
- example/server.js
- index.d.ts
- lib/defaultMetrics.js
- lib/metrics/gc.js
- test/metrics/gcTest.js
I've implemented GC monitoring using perf_hooks builtin module (no dependencies on third party native modules).
Unfortunately perf_hooks module does not provide ability to measure heap size before GC, so I do not report amount of garbage collected( like https://github.com/SimenB/node-prometheus-gc-stats does)
But this implementation reports GC duration percentiles(with split by GC type) which can be quite useful.
> feat: implement GC metrics collection without native(C++) modules

- CHANGELOG.md
- README.md
- index.d.ts
- lib/defaultMetrics.js
- lib/metrics/eventLoopLag.js
- test/metrics/eventLoopLagTest.js
Guys, I'm sorry for bothering you with one more pull request :-)
I've implemented more advanced event loop monitoring based on functionality provided by Node11.
perf_hooks.monitorEventLoopDelay() use libuv timer, so its measurements are more precise.
> feat: implement advanced event loop monitoring

- CHANGELOG.md
- README.md
- example/server.js
- index.d.ts
- lib/defaultMetrics.js
- lib/metrics/eventLoopLag.js
- lib/metrics/heapSizeAndUsed.js
- lib/metrics/heapSpacesSizeAndUsed.js
- lib/metrics/helpers/processMetricsHelpers.js
- lib/metrics/helpers/safeMemoryUsage.js
- lib/metrics/osMemoryHeapLinux.js
- lib/metrics/processCpuTotal.js
- lib/metrics/processHandles.js
- lib/metrics/processMaxFileDescriptors.js
- lib/metrics/processOpenFileDescriptors.js
- lib/metrics/processStartTime.js
- lib/metrics/version.js
- lib/registry.js
- test/defaultMetricsTest.js
- test/metrics/maxFileDescriptorsTest.js
Only the event loop "lag" is still async, see the in-src notes.
Fixes: https://github.com/siimon/prom-client/issues/180
---
This is a WIP, it lacks tests (though it passes the existing ones).
Open questions:
- should I rearrange the commits? There are some unrelated ones in the PR, I could pull them into a seperate PR set if wanted. I figured out a way to do this that doesn't change the lib/metrics interface for the defaults, for example, so the metrics changes are mostly cleanup and could be done with or without the removal of the timeout.
- are the lib/metrics/ used directly by anyone? I'd like to remove the do-nothing closures for many of them that are called on every collect but are a no-op.
- do we need to support reconfiguration of the default metrics on the ***same*** registry? I …
> fix: collect metrics on scrape, not timeout

- README.md
- index.d.ts
- lib/counter.js
- lib/defaultMetrics.js
- lib/gauge.js
- lib/metrics/heapSizeAndUsed.js
- lib/pushgateway.js
- lib/registry.js
- lib/util.js
- test/__snapshots__/counterTest.js.snap
- test/__snapshots__/gaugeTest.js.snap
- test/clusterTest.js
- test/counterTest.js
- test/defaultMetricsTest.js
- test/gaugeTest.js
- test/registerTest.js
Fixes:                                                                           
- https://github.com/siimon/prom-client/issues/310                               
- https://github.com/siimon/prom-client/issues/177                               
- https://github.com/siimon/prom-client/issues/289
> feature: remove all timestamp support

- CHANGELOG.md
- index.d.ts
`registerCollector()` and `collectors()` were added to the Registry, expose them in TS type.
> feat: improve Registry type by adding the collector functions

- CHANGELOG.md
- lib/metrics/version.js
- test/metrics/versionTest.js
Fixes #238
Looks like similar changes are needed for `process_max_fds` and `process_start_time_seconds`. I need to go but can work on those later.
> fix: set nodejs_version_info after resetting registry

- lib/metrics/heapSpacesSizeAndUsed.js
- lib/metrics/osMemoryHeap.js
- lib/metrics/processCpuTotal.js
- lib/metrics/processRequests.js
I found some useless (after #333) using of third parameter `timestamp` in `Gauge.prototype.set` and `Counter.prototype.inc` functions and removed it.
> fix: remove useless using timestamp param after #333

- README.md
Is there something more appropriate that should be put here? For example, is there anything that "keeps Node alive" that needs to be stopped that's missing?
> docs: update readme for interval removal fixes #352

- .eslintrc
- CHANGELOG.md
- lib/metrics/eventLoopLag.js
- lib/metrics/gc.js
- lib/metrics/helpers/safeMemoryUsage.js
- lib/metrics/osMemoryHeapLinux.js
- lib/metrics/processMaxFileDescriptors.js
- lib/metrics/processOpenFileDescriptors.js
Updates ESLint parser to 2019.
Removes unused `catch` bindings (supported by Node.js 10+).
> chore: remove unused catch bindings

- .github/workflows/nodejs.yml
- package.json
- test/gaugeTest.js
- test/histogramTest.js
- test/summaryTest.js
- test/timeWindowQuantilesTest.js
Also add Node 14 to CI.
~Lolex has been renamed to `@sinonjs/fake-timers`. Jest bundles it now, but this keeps the diff down~ meh, second commit uses it. Note that I fake system time to be `0` (epoch). This is the default when using `lolex`/`@sinonjs/fake-timers`, while Jest default to the current system real time. _Not_ setting this gives a bunch of failing tests (e.g. we expect seconds to match ms from `Date.now()` etc). That's a bug in our tests, but I don't think it should be fixed in this PR
> chore: upgrade to Jest 26

- CHANGELOG.md
- index.d.ts
This PR fixes the TypeScript typings for `startTimer`. 
```ts
// Old 
startTimer(labels?: LabelValues<T>): (labels?: LabelValues<T>) => void;
// New 
startTimer(labels?: LabelValues<T>): (labels?: LabelValues<T>) => number;
```
This corresponds to the actual return value of the `startTimer` function [here.](https://github.com/siimon/prom-client/blob/master/lib/histogram.js#L110)
> Fix startTimer return type

- CHANGELOG.md
- index.d.ts
This PR fixes a small error in the TypeScript typings.
The implementation does a simple lookup on an object type:
```
getSingleMetric(name) {
return this._metrics[name];
}
```
When supplied with a non-existent name, this will simply return `undefined` -- which is not reflected in the typings.
> fix(types): `Registry.getSingleMetric` may return `undefined`

- CHANGELOG.md
- README.md
- index.d.ts
- lib/metrics/eventLoopLag.js
- lib/metrics/gc.js
- lib/metrics/heapSizeAndUsed.js
- lib/metrics/heapSpacesSizeAndUsed.js
- lib/metrics/helpers/processMetricsHelpers.js
- lib/metrics/osMemoryHeap.js
- lib/metrics/processCpuTotal.js
- lib/metrics/processHandles.js
- lib/metrics/processMaxFileDescriptors.js
- lib/metrics/processOpenFileDescriptors.js
- lib/metrics/processRequests.js
- lib/metrics/processStartTime.js
- lib/metrics/version.js
- test/defaultMetricsTest.js
I believe this resolves https://github.com/siimon/prom-client/issues/224. I was also needing a mechanism like this for applying labels to worker processes when running in a clustered environment.
I did it a bit more generically than just the suggested `collectDefaultMetrics({includeWorkerId: true})` because our project setup prevents us from using lib/cluster.js. We're using a pm2 wrapper around our nodejs parent process which has some nuances when using the nodejs `cluster` module directly from lib/cluster.js. As such, this should appease a wider audience of users who just want to generically apply labels to default metrics (including myself)
> feat: added support for adding labels to default metrics

- CHANGELOG.md
- lib/summary.js
- test/__snapshots__/summaryTest.js.snap
- test/summaryTest.js
Fixes #262
Closes #263 (this replaces that PR, adding a test and changelog entry)
> fix: summary.observe should validate labels correctly

- CHANGELOG.md
- README.md
- index.d.ts
- lib/histogram.js
- test/histogramTest.js
Since PR #139, histograms are initialized to zero if they do not use any labels - however, there currently is no way to do the same for histograms with labels (without directly accessing the internals of the histogram from the outside, which is of course not a great solution).
Therefore, this PR adds a function that lets the user explicitly zero out the metrics for given labels. Since prom-client has no way of knowing what the values of the labels can be, it's up to the user to call this with all expected values.
> Add function for setting a Histogram to zero for given labels

- CHANGELOG.md
- lib/metrics/osMemoryHeapLinux.js
- test/defaultMetricsTest.js
I noticed that the following default metrics were missing labels that were configured in the `collectDefaultMetrics` method
- `process_resident_memory_bytes`
- `process_virtual_memory_bytes`
- `process_heap_bytes`
Looks like `osMemoryHeapLinux.js` missed out in #374 😢 . We just need to pass through the labels from the config to the metrics.
--- 
Thank you so much for this library! It's amazing that in a few simple steps we can all get amazing metrics from our Node.js servers. Cheers 🙇 😊
> fix: set labels for default memory metrics on linux

- example/histogram-1.js
- example/histogram-2.js
- example/histogram-3.js
Added examples showing how to use `observe `method on histogram when dealing with labels. Such examples existed for other types of metrics but not for histograms.
> added histogram example with observe method using labels

- CHANGELOG.md
- lib/metrics/gc.js
Fix #435
Node 16 deprecated `PerformanceEntry.kind`, moving it to `PerformanceEntry.detail.kind`.
Use `entry.detail.kind` if available. Fall back to deprecated `entry.kind`.
See https://nodejs.org/docs/latest-v16.x/api/deprecations.html#deprecations_dep0152_extension_performanceentry_properties
> Fix DEP0152 / deprecated PerformanceEntry.kind usage

- CHANGELOG.md
- README.md
- lib/metrics/eventLoopLag.js
These are not entirely accurate: they're the "mean of the mean" and "mean of percentiles," but that's as good as we can get.
No tests added - doesn't seem worth asserting that these properties are set.
Fixes #418
> Set aggregation method for newer event loop metrics

- CHANGELOG.md
- lib/gauge.js
- test/gaugeTest.js
Calling `.inc(value)` with a dynamic value that may be 0 or 1 will always cause to increase metrics by 1. This is very problematic and may distort the metrics in a non obvious way.
Closes https://github.com/siimon/prom-client/issues/447
> Use Nullish Coalescing Operator in inc()

- README.md
The docs for `collectDefaultMetrics` mention that the config object accepts a
`registry`, but the property is actually `register`.
> docs: fix config reference for `collectDefaultMetrics`

- CHANGELOG.md
- benchmarks/gauge.js
- benchmarks/index.js
- lib/counter.js
- lib/gauge.js
- lib/validation.js
No need to create and return new functions each time the gauge methods are called. Also saves ~40 LOC.
> Reduce memory allocations/improve perf of Gauge and Counter

- CHANGELOG.md
- lib/bucketGenerators.js
- test/bucketGeneratorsTest.js
Subsequent additions propagate rounding errors in the IEEE 754 model that JavaScript uses for its `number` type. This patch does not remove the possibility of rounding errors, but it removes the propagation of such errors to subsequent bucket bounds. This leads to a smaller error overall.
This might be considered a breaking change because it might change label values in the resulting metrics.
> Avoid propagating rounding errors in linearBuckets

- CHANGELOG.md
- index.d.ts
- test/registerTest.js
This property already exists, but the type declaration is missing.
Refs: https://github.com/siimon/prom-client/pull/91
> Add type declaration for client.contentType

- lib/metrics/eventLoopLag.js
This PR addresses problem described at #370. 
I've read attentively that issue and propositions about the solution. Anyway after own investigation of the code I've decided that simple calling `histogram.reset()` after each `collect()` invocation will be simply enough.
Event loop lag metrics is important for us because we want to see how our application handles spikes and how internal event loop lag increases, to determine easier, there is hiding the bottleneck. Currently we just cannot see that, because `nodejs_eventloop_lag_seconds` represents just single measurement result (so it is pretty random, as noticed already at #309) and `nodejs_eventloop_lag_mean_seconds` shows mean value for overall process lifetime and I cannot imagine, how to use such information in our case and for what …
> Reset internal histogram of monitorEventLoopDelay after each collect() invocation

- CHANGELOG.md
- index.d.ts
This fixes the registry's `getMetricsAsArray()` function type.
It appears to be currently incorrect as it does not return a promise:
https://github.com/siimon/prom-client/blob/4e6aacd4921a3791e8f01ac6ab2fd6bb421b0dc0/lib/registry.js#L21-L23
> fix getMetricsAsArray type

- CHANGELOG.md
- index.d.ts
- lib/gauge.js
- lib/summary.js
- test/gaugeTest.js
- test/summaryTest.js
For consistency with histograms, return the timed duration from the done function returned by `gauge.startTimer()` and `summary.startTimer()`.
Ref #465
> feat: return the timed duration from gauges and summaries

- CHANGELOG.md
- lib/defaultMetrics.js
The `processResources` metrics depend on the
`process.getActiveResourcesInfo()` API which is still experimental, so
we shouldn't remove the existing metrics in favour of that quite yet.
Signed-off-by: Darshan Sen <raisinten@gmail.com>
cc @zbjornson
> Preserve the `processRequests` and `processHandles` metrics

- CHANGELOG.md
- index.d.ts
Currently all the `Metric` types must receive a generic argument which must extend a string.
Adding a default value `string` so that users who just want to type `<string>` there, won't have to
> feat(types): add default types to metrics types

- CHANGELOG.md
- lib/gauge.js
- lib/util.js
**Motivation**
- Right now when using `gauge.inc()` or `gauge.dec()`, we call `hashObject()` 2 times
- It's better to call `hashObject()` once as in `counter.inc()`
**Description**
- New function `setValueDelta()` with a `hash` param
- `gauge.inc()` and `gauge.dec()` to call `setValueDelta()` via `setDelta()` function
> perf: improve performance of gauge inc() dec()

- CHANGELOG.md
- lib/pushgateway.js
- package.json
- test/pushgatewayTest.js
This PR allows to use the gzip Content-Encoding introduced with https://github.com/prometheus/pushgateway/pull/477.
> Support gzipped pushgateway requests

- index.js
- lib/metrics/gc.js
- lib/metrics/processHandles.js
- lib/metrics/processRequests.js
- lib/metrics/processResources.js
- package.json
> chore: update prettier

- README.md
It's a simple correction in the examples so that newbies don't get frustrated :)
i change `.then({ resp, body } => {` for `.then(({ resp, body }) => {` in all examples
specific error:
```
.then({ resp, body } => {
^^^^^^^^^^^^^
SyntaxError: Malformed arrow function parameter list
at wrapSafe (internal/modules/cjs/loader.js:915:16)
at Module._compile (internal/modules/cjs/loader.js:963:27)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
at Module.load (internal/modules/cjs/loader.js:863:32)
at Function.Module._load (internal/modules/cjs/loader.js:708:14)
at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
at internal/main/run_main_module.js:17:47
```
> Fix examples of push gateway in README.md

- CHANGELOG.md
- lib/metrics/gc.js
When using rollup to build an all-in-one esm module, rollup fails to properly handle require in try{}catch{} code.
It causes perf_hooks to not be defined ( that would happens if perf_hooks isn't implemented in current nodejs version) and breaks code accessing perf_hooks constants fields :
```js
perf_hooks.constants.NODE_PERFORMANCE_GC_MAJOR
```
It'd be nice to either require it (and as such require recent nodejs version) or make sure the codebase is compatible when it is not present.
This change is for enabling perf_hooks to not exists. It would also be possible to make it a hard requirement.
Note : `perf_hooks.constants` is defined only on nodejs version starting with the following :
1. >13.9.0
1. >12.17.0
Because of this I'm unsure the rest of the gc.js code will work correctly with …
> Fix incompatibility with perf_hooks accross nodejs versions

- CHANGELOG.md
- example/default-metrics.js
This updates the outdated sample output with the latest one we get when we
run the script using Node.js v18.12.1 on an x86_64 Ubuntu 20.04.
Signed-off-by: Darshan Sen <raisinten@gmail.com>
> Update the sample output in `example/default-metrics.js`

- CHANGELOG.md
- index.d.ts
**Current Limitation**
At the moment there is no clean way to get a single metric value programmatically while using typescript.
The following is not possible as it causes type issues as the getters are implemented in javascript but are missing from type definitions.
```ts
const metric = metrics.register.getSingleMetric("process_cpu_user_seconds_total");
// Property 'get' does not exist on type 'Metric<string>'
const {value} = (await metric.get()).values[0]
```
**Solution**
Add `get` method to type definitions of each metric classes and define `MetricObjectWithValues` type which is returned by getters.
> fix: add get method to type definitions of metric classes

- README.md
`getSingleMetric` is a synchronous function, don't need to `await` it 😅 
ref: https://github.com/siimon/prom-client/blob/master/lib/registry.js#L132
> docs(README): remove await of getSingleMetric

- CHANGELOG.md
- lib/registry.js
When looking at some CPU profiles of metric -> string serialization, I noticed that escaping all of the strings and labels was showing up in the flamegraph more than I would expect. This isn't a massive win by any means, but it's pretty consistently ~20% faster on a microbenchmark: https://jsbench.me/qklez5ombn/1. I'll take 20%.
Some notes:
1) The benchmarks literally don't test this case, as far as I can tell. None of the registry benchmarks have quotes or newlines or anything in the labels? An A/A test (master vs. 14.2.0) was producing inconsistent results, so I'm not quite sure I trust that benchmark anyway.
2) Correctness-wise, this should work. Replacing the `\` before replacing the `\n` fixes the case that made you need the `.replace(/\\(?!n)/g, '\\\\')` regex in the first place, so …
> perf: swap order of escape regexes to avoid lookahead

- CHANGELOG.md
- lib/registry.js
Use `Array.prototype.join` instead string concatenation for constructing Prometheus metric string. This results in improved performance and reduced memory consumption, especially when there's a large amount of dimensions (labels and label values). In addition uses array iteration methods instead of explicit loops.
**note**: there are no tests for exemplar so I could not verify that this functionality works as expected.
> perf: improve performance of getMetricAsString in next

- CHANGELOG.md
- lib/pushgateway.js
When using gzip `Content-Encoding` the DELETE requests sent to a pushgateway server fail with error code 400. With this PR we disable `Content-Encoding` option, if found, for DELETE requests.
> fix: Disable content encoding for pushgateway delete requests

- CHANGELOG.md
- lib/registry.js
- test/__snapshots__/exemplarsTest.js.snap
- test/__snapshots__/registerTest.js.snap
- test/exemplarsTest.js
- test/registerTest.js
Fix exemplar formating
- Fixed improper formating of exemplars
- Added snapshot test for exemplars
Fixes https://github.com/siimon/prom-client/issues/554
> fix: correct exemplar formating

- CHANGELOG.md
- lib/histogram.js
- lib/registry.js
Cleans up and compacts the code.
> perf: improve perf by refactoring code to be cleaner and more efficient

- CHANGELOG.md
- index.d.ts
1. Content types was mixed up -  #565 
2. Methods like collectDefaultMetrics without setting generic type does not allows to work with Registry<OpenMetricsContentType>
> Fix typescript definitions for using with Registry<OpenMetricsContentType>

- CHANGELOG.md
- README.md
- index.d.ts
Fixes #568 
This was broken since the change in #167 in v11.0.0
> Fixes description for setToCurrentTime to seconds instead of milliseconds

- CHANGELOG.md
- lib/pushgateway.js
- test/pushgatewayTest.js
Throw an error if the gateway rejected the pushed metrics.
> fix: do not ignore error if request fails

- .github/workflows/nodejs.yml
- CHANGELOG.md
- package.json
Node 16 is EOL now. I'm fine keeping that around, but also keeping v14 around seems unnecessary
> chore: drop node 14

- CHANGELOG.md
- lib/pushgateway.js
- test/pushgatewayTest.js
As explained in [README.md](https://github.com/siimon/prom-client/blob/master/README.md?plain=1#L575) the timeout option should timeout the request but it is not doing it.
It was missing listen to the timeout event from `node HTTP` and rejecting the promise (destroying the request).
> fix: pushgateway reject with timeout

- CHANGELOG.md
- lib/metrics/osMemoryHeapLinux.js
A little simplification with single `reduce` instead of `filter`+`forEach`. And `startsWith` instead of `indexOf`.
> perf: refactored structureOutput with single reduce

- CHANGELOG.md
- lib/counter.js
- lib/gauge.js
- lib/histogram.js
- lib/metric.js
- lib/summary.js
- lib/util.js
Since label names are predefined ahead-of-time and constant during
runtime, we can sort them before-hand and use them when running `hashObject`.
Running on node v18.18.2.
Note: the registry benchmarks I couldn't run because of OOM (and on master branch as well).
```
http fetch GET 200 https://registry.npmjs.org/prom-client 83ms
http fetch GET 200 https://registry.npmjs.org/prom-client/-/prom-client-15.0.0.tgz 42ms
+ prom-client@15.0.0
added 4 packages from 4 contributors and audited 4 packages in 0.382s
found 0 vulnerabilities
- histogram ➭ observe#1 with 64 ➭ current x 104,381 ops/sec ±0.42% (99 runs sampled)
- histogram ➭ observe#1 with 64 ➭ prom-client@latest x 103,709 ops/sec ±0.72% (96 runs sampled)
- histogram ➭ observe#2 with 8 ➭ current x 68,178 ops/sec ±0.20% (98 runs sampled)
- …
```
> Improve performance of `hashObject`

- CHANGELOG.md
- README.md
- lib/pushgateway.js
- test/pushgatewayTest.js
intended for compatibility with gravel gateway (https://github.com/sinkingpoint/prometheus-gravel-gateway)
see issue https://github.com/siimon/prom-client/issues/502
> pushgateway: adds configuration for omitting job name

- CHANGELOG.md
- index.d.ts
- lib/histogram.js
- test/exemplarsTest.js
When using `Histogram.startTimer()` with 'enableExemplars' option set to true in order to record duration, it throws an error as following.
It supposed to work normally as it does when 'enableExemplars' option set to false.
Plus, it would be better if we could provide adding exemplarLabels just like we could do with `Histogram.observe()`.
I have added the feature with regarding test cases. Please feel free to give me any feedback.
> feat: startTimer with exemplar

- .gitignore
- CHANGELOG.md
- example/histogram-large-memory.js
- lib/histogram.js
We have a use case where it generates a huge amount of histograms, each has more than 10 labels, we found the memory usage is quite high, under this scenario, we did an experiment and found that removing bucketExemplars field from histograms could save about `27%` memory usage for each histogram instance, hope the maintainers could review and consider it
> perf: improve the memory usage of histogram

- .editorconfig
- .github/workflows/ci.yml
- CHANGELOG.md
- lib/metrics/eventLoopLag.js
- lib/metrics/heapSpacesSizeAndUsed.js
Catch [error thrown by bun.js](https://github.com/oven-sh/bun/blob/801e475c72b3573a91e0fb4c3afdd53b437770e1/src/js/node/perf_hooks.ts#L158) when calling `perf_hooks.monitorEventLoopDelay`
Following up on https://github.com/siimon/prom-client/pull/599 - bun.js already introduced some of the missing APIs (or created stubs) so to the best of my knowledge this is the last thing which is required to make default gc stats work for bun (at least it worked for me with this change).
Error is also reported in bun's repository - https://github.com/oven-sh/bun/issues/4708#issuecomment-2030436691
Fixes https://github.com/siimon/prom-client/issues/570
Closes https://github.com/siimon/prom-client/issues/623
> fix: enable bun.js by catching NotImplemented error

- CHANGELOG.md
- index.d.ts
> fix: add missing Registry types

- CHANGELOG.md
- index.d.ts
- index.js
It currently just reads the default prop, and then no longer affect or reflect reality
> fix: correctly get and set top level `contentType` property

- .eslintrc
- index.d.ts
- package.json
Opening up the `d.ts` file in my IDE gave a parsing error from ESLint
> chore: add ts-eslint

- CHANGELOG.md
- lib/util.js
- test/__snapshots__/counterTest.js.snap
- test/__snapshots__/histogramTest.js.snap
- test/__snapshots__/summaryTest.js.snap
- test/utilTest.js
This fix ensures consumers of the library get more insights into which labels are causing an error to occur. 
With the new error message it is easier for a developer to debug what happened in the case where you accidentally pass in a bad argument.
If `getLabels` gets called like this:
```js
getLabels(['label1', 'label2'], ['arg1']);
```
it used to throw...
```
Error: Invalid number of arguments
at exports.getLabels 
```
now it throws this:
```
Error: Invalid number of arguments: "arg1" for label names: "label1,label2".
at exports.getLabels 
```
> Improve error message on labels

- .github/workflows/ci.yml
When there are lint failures, it's super noisy as all test runs fail (and they take longer than necessary). Splitting it out makes sense
> chore(ci): run lint checks separately from tests

- .eslintrc
- .husky/pre-commit
- benchmarks/index.js
- lib/metrics/eventLoopLag.js
- lib/pushgateway.js
- package.json
Why not
Also migrates from `eslint-plugin-node` to `eslint-plugin-n` as the former is unmaintained and replaced
> chore: update prettier and husky

- README.md
new client.Counter should initiate counter variable and not gauge
> Update README.md - fix wrong variable name

- CHANGELOG.md
- index.d.ts
Consider the following code:
```ts
const histogram = new Histogram({
name: 'example',
help: 'Example',
buckets: [0, 1, 4],
})
const timer = histogram.startTimer()
timer({ 'should_not_pass_because_there_is_no_label_name_defined': 'oops' })
```
This example passes the type checker because `Histogram<T>`'s `T` inferred by `TypeScript` is `string`, which allows `timer` to accept any `Record<string, string | number>` when there's no label defined.
The generic `Metric<T extends string>` type now defaults its label name generic `T` to `NoLabelNameType`. This provides better type inference for metrics that do not have labels.
> feat: update default type for metrics to `NoLabelNameType`

- CHANGELOG.md
- lib/counter.js
- lib/gauge.js
- lib/histogram.js
- lib/registry.js
- lib/summary.js
- lib/util.js
As of sometime around the middle of Node 16, the performance of Map for long-lived, mutable objects exceeded that of {}. I believe this gap is more pronounced in Node 18 as well.
The deal is that the representation for Objects that repeatedly change turns into a weird chain that occupies (in my benchmarks at least) ~40% more memory. So once v8 made Map.set/get faster than map[], we all should have switched to Maps and Sets.
Between the slightly faster functions and the lower memory pressure this can create a notable improvement.
Making a change like this on my last project for a long lived cache resulted in much better memory behavior and also about a 5% improvement in TTFB - just from changing a popular lookup table.
Note that the final change in this PR constitutes a change for anyone …
> perf: Utilize Maps for metric collection 

- CHANGELOG.md
- benchmarks/histogram.js
- lib/histogram.js
- lib/metrics/helpers/processMetricsHelpers.js
- lib/registry.js
Also add missing benchmarks for startTimer(), since I'm mucking about in its innards.
In theory removing call() for arrow functions or straight calls improves performance, but I've never managed a benchmark that proves it. This change also reduces closure creation but GC is also difficult to benchmark. Make enough of these changes however and you can get yourself a little teeny tiny notch in your telemetry data that proves you did something (I think I clocked my test case at about .8%, because the calls were slow and so that added up to 5+ms). 
So these are officially just about improving single step debugging. 
One of the places where Prometheus can outshine OpenTelemetry is in trying to figure out why your metrics are confusing/missing/garbled. If you've ever tried to single-step …
> Reduce function indirection in histogram.js for easier debugging

- CHANGELOG.md
- lib/cluster.js
- test/clusterTest.js
Fix for memory leak and excess computation caused by responses showing
up after the timeout has exceeded.
This introduces some load shedding capability for if the cluster primary cannot keep up with the responses from the cluster.
Make done() unconditionally responsible for calling requests.delete()
This should also handle memory leaks where a cluster member crashes before sending a reply to a collection request.
fixes #677, improves #628
> Fix for memory leak and avoid processing expired responses

- CHANGELOG.md
- benchmarks/cluster.js
- benchmarks/counter.js
- benchmarks/gauge.js
- benchmarks/index.js
- benchmarks/registry.js
- benchmarks/utils/labels.js
- lib/counter.js
- lib/gauge.js
- lib/histogram.js
- lib/metric.js
- lib/metricAggregators.js
- lib/registry.js
- lib/summary.js
- lib/util.js
- package.json
- test/gaugeTest.js
- test/utilTest.js
This change consolidates a lot of util code into a single object that can guarantee that the functionality is all used consistently, which gets the metrics out of the job of managing labelNames and their sorting.
This results in a 20-45% improvement in benchmark time for most of the metric types. Gauges with no labels act weird, but if you disable the counter tests this mostly goes away, suggesting testing artifacts. The benefits are more substantial for metrics with label (which IME is 'every singe metric you have', but may result in a slight decline in the no-label path.
However, since the no-label path has historically been **nearly 500 times faster** than the label scenario, this is not a real problem. The amortized cost of the entire system is greatly reduced by optimizing for the …
> Performance: New storage engine for stats, with improved key management
