- package.json
With the latest change that has been made, the version number should be updated.
> Updated version number to 3.4.1

- lib/gauge.js
- lib/histogram.js
- lib/summary.js
- lib/util.js
- package.json
...and replace with custom function in lib/util.js
Improves performance of metric updates by several orders of magnitude.
> Eliminate dependency on the object-hash package

- README.md
Makes it prettier 😄 
Before:
After:
> Add syntax highlighting to samples in readme

- .gitignore
- package.json
Also ignore log files.
Before:
```
-rw-r--r--  1 1115076382  1503010931   845 Sep  1 10:14 package/package.json
-rw-r--r--  1 1115076382  1503010931    30 Sep  1 10:14 package/.npmignore
-rw-r--r--  1 1115076382  1503010931  4258 Aug 31 15:56 package/README.md
-rw-r--r--  1 1115076382  1503010931 11341 Aug 31 15:56 package/LICENSE
-rw-r--r--  1 1115076382  1503010931   682 Sep  1 10:11 package/index.js
-rw-r--r--  1 1115076382  1503010931    18 Aug 31 15:56 package/.travis.yml
-rw-r--r--  1 1115076382  1503010931  1285 Aug 31 15:56 package/.eslintrc
-rw-r--r--  1 1115076382  1503010931   995 Aug 31 15:56 package/example/server.js
-rw-r--r--  1 1115076382  1503010931   741 Aug 31 15:56 package/lib/bucketGenerators.js
-rw-r--r--  1 1115076382  1503010931  2318 Aug 31 15:56 …
```
> Only include relevant files in package

- lib/register.js
- test/counterTest.js
- test/gaugeTest.js
- test/histogramTest.js
- test/metrics/heapSizeAndUsedTest.js
- test/registerTest.js
- test/summaryTest.js
Prometheus isn't able to parse it, no reason not to fail hard
> Throw on duplicate metrics

- lib/metrics/eventLoopLag.js
- lib/metrics/heapSizeAndUsed.js
- lib/metrics/processHandles.js
- lib/metrics/processRequests.js
- test/metrics/eventLoopLagTest.js
- test/metrics/processHandlesTest.js
- test/metrics/processRequestsTest.js
> Update description of new metrics

- README.md
Extracted @tcolgate's implementation from their fork. Feedback appreciated!
> Add link to GC module

- lib/defaultMetrics.js
- lib/metrics/eventLoopLag.js
- lib/metrics/heapSizeAndUsed.js
- lib/metrics/osMemoryHeap.js
- lib/metrics/osMemoryHeapLinux.js
- lib/metrics/processCpuTotal.js
- lib/metrics/processHandles.js
- lib/metrics/processMaxFileDescriptors.js
- lib/metrics/processOpenFileDescriptors.js
- lib/metrics/processRequests.js
- lib/metrics/processStartTime.js
- test/defaultMetrics.js
ping @SimenB, a better solution imo, any comments?
> Remove all default metrics on initalization (#44)

- lib/metrics/processOpenFileDescriptors.js
Typo meant it was never included...
> Fix check for open FDs

- lib/metrics/processMaxFileDescriptors.js
Ref https://github.com/siimon/prom-client/pull/46#issuecomment-249113108
> Parse `maxFds` into a number

- lib/counter.js
- lib/gauge.js
- lib/histogram.js
- lib/summary.js
This is PR https://github.com/siimon/prom-client/pull/66 with clean history.
Also I've removed unused `createValue` variable from some files (it also probably should look like `var createValue = require('./util').setValue;`, but in any case it's not used in code, so I think removing it is a good idea).
> Fix array jsdoc and remove unused variables

- index.d.ts
This PR adds missing getSingleMetric method to typings
> Add missing getSingleMetric to typings

- README.md
- example/server.js
- index.js
- lib/register.js
Fixes #84
https://prometheus.io/docs/instrumenting/exposition_formats/#format-variants-comparison
> Export expected content type

- package.json
> Upgrade outdated deps

- index.d.ts
Related: https://github.com/siimon/prom-client/pull/97, see comments
> Updated typedef for getSingleMetricAsString()

- README.md
- lib/counter.js
- lib/gauge.js
- lib/register.js
- lib/util.js
- test/counterTest.js
- test/gaugeTest.js
- test/registerTest.js
According to exposition format specification https://prometheus.io/docs/instrumenting/exposition_formats/
> Add timestamp field support

- README.md
- lib/metrics/eventLoopLag.js
- lib/metrics/heapSizeAndUsed.js
- lib/metrics/heapSpacesSizeAndUsed.js
- lib/metrics/osMemoryHeap.js
- lib/metrics/osMemoryHeapLinux.js
- lib/metrics/processCpuTotal.js
- lib/metrics/processHandles.js
- lib/metrics/processMaxFileDescriptors.js
- lib/metrics/processOpenFileDescriptors.js
- lib/metrics/processRequests.js
- lib/metrics/processStartTime.js
- lib/metrics/version.js
> Add timestamp to default metrics

- README.md
- index.d.ts
- index.js
- lib/defaultMetrics.js
- test/defaultMetrics.js
> Move collection of default metrics inside an explicit function call

- lib/metrics/heapSpacesSizeAndUsed.js
No need to get new date in loop.
> Move out new date from loop

- lib/metrics/processMaxFileDescriptors.js
- lib/metrics/processStartTime.js
- lib/metrics/version.js
- package.json
> Remove timestamp from static metrics.

- .eslintignore
- .gitignore
- package.json
- test/.eslintrc
- test/bucketGeneratorsTest.js
- test/counterTest.js
- test/defaultMetricsTest.js
- test/gaugeTest.js
- test/histogramTest.js
- test/metrics/eventLoopLagTest.js
- test/metrics/heapSizeAndUsedTest.js
- test/metrics/heapSpacesSizeAndUsedTest.js
- test/metrics/processHandlesTest.js
- test/metrics/processRequestsTest.js
- test/metrics/versionTest.js
- test/pushgatewayTest.js
- test/pushgatewayWithPathTest.js
- test/registerTest.js
- test/summaryTest.js
- test/validationTest.js
I much prefer jest these days, so thought I'd take a crack at converting the tests. This was basically just running `jest-codemods`, so no hard feelings if you don't want it 🙂
> Use jest for tests

- CHANGELOG.md
- lib/metrics/heapSpacesSizeAndUsed.js
- package.json
- test/pushgatewayTest.js
- test/pushgatewayWithPathTest.js
- test/validationTest.js
> Node 4 package.json changes

- .eslintrc
- lib/summary.js
> Remove unused functions

- .eslintrc
- CHANGELOG.md
- lib/counter.js
- lib/defaultMetrics.js
- lib/gauge.js
- lib/histogram.js
- lib/pushgateway.js
- lib/summary.js
- test/defaultMetricsTest.js
- test/registerTest.js
> Use object shorthand

- CHANGELOG.md
- lib/counter.js
- lib/gauge.js
- lib/histogram.js
- lib/summary.js
- package.json
> Remove util-extend

- index.d.ts
Missing from #107 I guess.
@SkeLLLa is this correct syntax?
> Make merge static in ts typings

- package.json
- test/metrics/heapSpacesSizeAndUsedTest.js
- test/pushgatewayTest.js
- test/pushgatewayWithPathTest.js
This makes the tests slower (as it just sets up an actual express server instead of mocking out the requests), but at least they pass.
> Make tests pass in node 8

- index.d.ts
- package.json
I like doing this. That way, you don't really have to formatting the code as you go. Just commit, and it'll be reformatted for you.
If you really want to commit regardless, you can do `--no-verify` (which it will tell you to do if it fails, so no googling necessary).
This commit also formats the d.ts file, cuz why not 🙂
> Add precommit hook to format code

- CHANGELOG.md
- index.js
- lib/counter.js
- lib/defaultMetrics.js
- lib/gauge.js
- lib/histogram.js
- lib/pushgateway.js
- lib/register.js
- lib/registry.js
- lib/summary.js
- lib/util.js
- test/metrics/heapSizeAndUsedTest.js
- test/metrics/heapSpacesSizeAndUsedTest.js
Piecemeal #117
This diff should be viewed without whitespace changes, as the indentation has changed.
https://github.com/siimon/prom-client/pull/125/files?w=1
> Convert prototype to classes

- CHANGELOG.md
- index.d.ts
- lib/counter.js
- lib/gauge.js
- lib/histogram.js
- lib/summary.js
- lib/util.js
Since the next is a major anyways, might get this is.
> Print deprecation warnings on deprecated constructors

- .editorconfig
- .eslintrc
- CHANGELOG.md
- README.md
- lib/histogram.js
- lib/util.js
- lib/validation.js
- package.json
Consistent style all around 😀 WDYT?
Use https://github.com/siimon/prom-client/pull/164/files?w=1 to see the actual diff without the whitespace noise
> Use prettier on markdown and json

- .travis.yml
- CHANGELOG.md
- appveyor.yml
- package.json
@SimenB do you know any more place where we have node versions configured?
> Dropped node 4 support

- CHANGELOG.md
- lib/counter.js
- test/__snapshots__/counterTest.js.snap
- test/counterTest.js
This is the fix for #189 
fixes #189
> Validate labels on inc on counters

- index.d.ts
add `maxAgeSeconds` and `ageBuckets`
> Update types for SummaryConfiguration

- .travis.yml
- appveyor.yml
> chore: fix appveyor build

- CHANGELOG.md
- lib/cluster.js
Fixes https://github.com/siimon/prom-client/issues/293.
> Lazy-load cluster module to fix Passenger support

- .github/workflows/nodejs.yml
- .gitignore
Add cache handling to the CI and also add package-lock.
Will improve speed by not polling from `npm` at each run
With cache : 1m15s
Without cache : 2m9s
> [CI] Add cache handling

- CHANGELOG.md
- lib/registry.js
This refactor a little sketchy pattern.
> Minor refactor

- CHANGELOG.md
- index.d.ts
- lib/counter.js
- lib/gauge.js
- lib/histogram.js
- lib/metric.js
- lib/summary.js
- lib/util.js
Net -155 lines.
Started working on async changes, but want to get this deduplication done so that the async changes are smaller.
> chore: refactor metrics to reduce code duplication

- .github/workflows/changelog.yml
- CHANGELOG.md
Added a github action to make sure the changelog has been updated when opening up a pull request
This closes #344
> Added changelog check

- example/cluster.js
- lib/cluster.js
Fixes #382
This one's hard to test without forking processes...
> bug: fix regression in 4e6aacd

- package.json
> chore: update eslint and typescript to latest

- CHANGELOG.md
- example/pushgateway.js
While trying to get up to speed and understand how to use the pushgateway api i got stuck not understanding
how to use the api. I have created a working example for how to send a counter metric to pushgateway. Was Thinking it might be useful to someone else to have a complete example of how to use it.
> a complete working example of a pushgateway push

- CHANGELOG.md
- lib/pushgateway.js
- test/pushgatewayTest.js
Added tests for push gateway awaiting on registry.metrics() #390 
Includes the fix proposed in https://github.com/siimon/prom-client/pull/392/files#r487438436
> Fix push gateway attempting to write promise instead of awaiting

- CHANGELOG.md
- README.md
- example/counter.js
- example/default-metrics.js
- example/gauge.js
- example/histogram-1.js
- example/histogram-2.js
- example/histogram-3.js
- example/histogram-4.js
Not sure if this is of value? I find examples like this useful to run from the command line to get an idea of how something functions.
> docs: examples with recorded output

- CHANGELOG.md
- README.md
- example/pushgateway.js
- lib/pushgateway.js
- package.json
- test/pushgatewayTest.js
Fix #416 
:warning: breaking change on pushgateway methods.
> Promisify pushgateway methods

- .github/workflows/nodejs.yml
Also use built-in caching of `actions/setup-node`
> chore: test using node 17

- .npmrc
We ignore the lockfile, so let's not generate one either: https://github.com/siimon/prom-client/blob/0cf38e85047d0ac1d2051007280c6bcdc159530e/.gitignore#L6
> chore: add .npmrc

- lib/histogram.js
- package.json
> chore: upgrade prettier to v3
